# Generated by Django 4.0.2 on 2022-06-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=11)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DisabledDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('vci', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('buy_order', models.CharField(max_length=26)),
                ('session_id', models.CharField(max_length=61)),
                ('card_number', models.CharField(max_length=19)),
                ('accounting_date', models.CharField(max_length=4)),
                ('transaction_date', models.CharField(max_length=24)),
                ('authorization_code', models.CharField(max_length=6)),
                ('payment_type_code', models.CharField(max_length=10)),
                ('response_code', models.IntegerField()),
                ('installments_amount', models.IntegerField(blank=True, null=True)),
                ('installments_number', models.IntegerField()),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('token', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('booking_date', models.DateField()),
                ('block', models.CharField(max_length=11)),
                ('visitants', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
                ('school', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('booking_date', models.DateField()),
                ('block', models.CharField(max_length=11)),
                ('visitants', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
                ('school', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=30)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.payment')),
            ],
        ),
    ]
